server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8762
  server:
    wait-time-in-ms-when-sync-empty: 5