server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://2.2.2.2:8761
  server:
    wait-time-in-ms-when-sync-empty: 5